scsi_error: send device reset if asynchronous abort failed
The current SCSI EH implementation requires us to enter the error
handler before a device reset can be send, causing us to wait for
all outstanding commands on the _host_ before a device reset can be
issued.
But a device reset has a very well device scope, so there really should
not be any implications to _other_ devices on the same host when the
device reset is issued.
So it should be possible to issue a device reset directly from
scsi_eh_abort_handler() once a command abort fails without having to
wait for outstanding commands on any other devices on the same host.
This will abort any outstanding command _on the same_ device, but
as the command abort failed we'll have to reset the device anyway.

Signed-off-by: Hannes Reinecke <hare@kernel.org>